CC=gcc
CFLAGS = -std=c11 -Wall -Wextra -Werror
LFLAGS = -lm
NAME = Sport_Manager
# nazwa programu wynikowego
SRC = main.c funkcje.c
# nazwy wszystkich plikow zrodlowych
OBJS = main.o funkcje.o

# nazwy wszystkich modulow
$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME) $(LFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJS) $(NAME)
